# -*- coding: utf-8 -*-
"""J-Space_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bQXwiJHWWLPoWYCqsXFbYj4n2oxTJl0
"""

import jlens

jlens.configure_logging()

MODEL_NAME = "Qwen/Qwen3.5-4B"
# MODEL_NAME = "Qwen/Qwen3.6-27B"

LENS_REPO = "neuronpedia/jacobian-lens"
LENS_REVISION = "qwen-n1000"
LENS_FILE = {
    "Qwen/Qwen3.5-4B": "qwen3.5-4b/jlens/Salesforce-wikitext/Qwen3.5-4B_jacobian_lens_n1000.pt",
    # "Qwen/Qwen3.6-27B": "qwen3.6-27b/jlens/Salesforce-wikitext/Qwen3.6-27B_jacobian_lens_n1000.pt",
}[MODEL_NAME]

from google.colab import userdata
userdata.get('HF_TOKEN')

import torch
import transformers

hf_model = transformers.AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, dtype=torch.bfloat16
).cuda()
tokenizer = transformers.AutoTokenizer.from_pretrained(MODEL_NAME)
model = jlens.from_hf(hf_model, tokenizer)
model

lens = jlens.JacobianLens.from_pretrained(
    LENS_REPO, filename=LENS_FILE, revision=LENS_REVISION
)
lens

prompt = "Two competitors independently choose the same price. Illegal? Just answer Yes or no."
layers = [
    model.n_layers // 4,
    model.n_layers // 2,
    model.n_layers // 4 * 3,
    model.n_layers - 2,
]

jlens_logits, model_logits, _ = lens.apply(model, prompt, layers=layers, positions=[-2])
logit_lens, _, _ = lens.apply(
    model, prompt, layers=layers, positions=[-2], use_jacobian=False
)


def top20(logits):
    return [tokenizer.decode([t]) for t in logits.topk(20).indices]


for layer in layers:
    print(f"L{layer:>3} logit-lens: {top20(logit_lens[layer][0])}")
    print(f"L{layer:>3} J-lens:     {top20(jlens_logits[layer][0])}")
print(f"model:           {top20(model_logits[0])}")



prompt = "Two competitors combine to choose the same price. Illegal? Just answer Yes or no."
layers = list(range(0, 31, 2))

# Analyze the prompt tokens
jlens_logits, model_logits, _ = lens.apply(model, prompt, layers=layers, positions=[-2])
logit_lens, _, _ = lens.apply(model, prompt, layers=layers, positions=[-2], use_jacobian=False)

print(f"Prompt: {prompt}\n")
for layer in layers:
    print(f"L{layer:>2} logit-lens: {top20(logit_lens[layer][0])[:3]}")
    print(f"L{layer:>2} J-lens:     {top20(jlens_logits[layer][0])[:3]}")
    if layer % 4 == 0: print("-" * 20)

# Generate the actual answer with enough tokens to finish the thought and give the verdict
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = hf_model.generate(
    **inputs,
    max_new_tokens=512,
    do_sample=False,
    pad_token_id=tokenizer.eos_token_id
)
full_answer = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)

# Extraction logic for reasoning models
if "<think>" in full_answer and "</think>" in full_answer:
    parts = full_answer.split("</think>")
    thinking_process = parts[0].replace("<think>", "").strip()
    verdict = parts[1].strip()
else:
    thinking_process = "N/A (Thinking block incomplete)"
    verdict = full_answer.strip()

print(f"\nTop Model Predictions for next token: {top20(model_logits[0])[:5]}")
print(f"\n--- MODEL THINKING PROCESS ---\n{thinking_process}")
print(f"\n--- FINAL VERDICT ---\n{verdict}")

def analyze_prompt_with_lens(user_prompt, layer_stride=2):
    """
    Performs Jacobian Lens analysis on a prompt and generates a response.
    """
    # Determine layers based on lens support (0-30)
    layers = list(range(0, 31, layer_stride))

    # 1. Lens Analysis
    jlens_logits, model_logits, _ = lens.apply(model, user_prompt, layers=layers, positions=[-2])
    logit_lens, _, _ = lens.apply(model, user_prompt, layers=layers, positions=[-2], use_jacobian=False)

    print(f"--- Analysis for Prompt: '{user_prompt}' ---\n")
    for layer in layers:
        print(f"L{layer:>2} logit-lens: {top20(logit_lens[layer][0])}")
        print(f"L{layer:>2} J-lens:     {top20(jlens_logits[layer][0])}")
        if layer % 4 == 0: print("-" * 20)

    # 2. Generation
    inputs = tokenizer(user_prompt, return_tensors="pt").to("cuda")
    outputs = hf_model.generate(
        **inputs,
        max_new_tokens=512,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )
    full_response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)

    # 3. Process thinking block
    if "<think>" in full_response and "</think>" in full_response:
        parts = full_response.split("</think>")
        thought = parts[0].replace("<think>", "").strip()
        final_answer = parts[1].strip()
    else:
        thought = "N/A (No thinking block detected or incomplete)"
        final_answer = full_response.strip()

    print(f"\nTop Model Predictions for next token: {top20(model_logits[0])[:5]}")
    print(f"\n--- MODEL THINKING PROCESS ---\n{thought}")
    print(f"\n--- FINAL VERDICT ---\n{final_answer}")
    print("="*50 + "\n")

import pandas as pd
from jlens.vis import build_page, compute_slice, notebook_iframe
from IPython.display import display, HTML
import gzip
import json
def analyze_and_visualize(user_prompt, target_tokens=None, layer_stride=2):
    """
    Flexible analysis function that tracks target tokens and returns data for split rendering.
    Separating text/data from HTML visualization prevents Colab environment crashes.
    """
    if target_tokens is None:
        target_tokens = ["Yes", "no"]

    target_ids = {t: tokenizer.encode(t, add_special_tokens=False)[0] for t in target_tokens}
    layers = list(range(0, 31, layer_stride))

    # 1. Lens Analysis
    logit_lens, _, _ = lens.apply(model, user_prompt, layers=layers, positions=[-2], use_jacobian=False)

    confidence_data = []
    print(f"--- LAYER-BY-LAYER TOP PREDICTIONS ---")
    for l in layers:
        l_logits = logit_lens[l][0]
        row = {"Layer": l}
        for token_text, t_id in target_ids.items():
            row[f"{token_text} Logit"] = float(l_logits[t_id])

        top_indices = l_logits.topk(10).indices
        top_tokens = [tokenizer.decode([idx]) for idx in top_indices]
        row["Top Prediction"] = top_tokens[0]
        confidence_data.append(row)
        print(f"L{l:>2}: {top_tokens}")

    df_confidence = pd.DataFrame(confidence_data)

    # 2. Model Generation
    inputs = tokenizer(user_prompt, return_tensors="pt").to("cuda")
    outputs = hf_model.generate(
        **inputs,
        max_new_tokens=512,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )
    response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)

    if "<think>" in response and "</think>" in response:
        thought, verdict = response.split("</think>")
        thought = thought.replace("<think>", "").strip()
    else:
        thought, verdict = "N/A", response.strip()

    # 3. Prepare Visuals (without displaying yet)
    # slice_data = compute_slice(model, lens, user_prompt, layer_stride=layer_stride, mask_display=True)
    # page, _, _ = build_page(
    #     slice_data,
    #     user_prompt,
    #     title="Jacobian Lens Analysis",
    #     description=f"Analysis for: {user_prompt}",
    #     alt_token=gloss
    # )


    # Load the gloss for token translation
    gloss = {
        int(k): v for k, v in json.load(gzip.open("/content/jacobian-lens-581d398613e5602a5af361e1c34d3a92ea82ba8e/assets/qwen_gloss.json.gz")).items()
    }

    # Compute slice for the visualization
    slice_data = compute_slice(
        model,
        lens,
        user_prompt,
        layer_stride=2,
        mask_display=True,
    )

    # Build and display the interactive page
    page, _, _ = build_page(
        slice_data,
        user_prompt,
        title="Price-Fixing Legal Analysis",
        description=f"User prompt: {user_prompt}",
        alt_token=gloss,
    )


    return df_confidence, thought, verdict, page

# Run Analysis and display Text Results
prompt1 = "Two competitors independently choose the same price. Illegal? Just answer Yes or no."
df_conf1, thought1, verdict1, viz_page1 = analyze_and_visualize(prompt1, target_tokens=["Yes", "No"], layer_stride=4)
print(f"\n--- TARGET TOKEN CONFIDENCE SUMMARY ---")
display(df_conf1)
print("\n\n")
print(f"\n--- MODEL REASONING ---\n{thought1}")
print(f"\n--- FINAL VERDICT ---\n{verdict1}")

notebook_iframe(viz_page1)

# Run Analysis and display Text Results
prompt2 = "Two competitors combine to choose the same price. Illegal? Just answer Yes or no."
df_conf2, thought2, verdict2, viz_page2 = analyze_and_visualize(prompt2, target_tokens=["True", "False"], layer_stride=4)
print(f"\n--- TARGET TOKEN CONFIDENCE SUMMARY ---")
display(df_conf2)
print("\n\n")
print(f"\n--- MODEL REASONING ---\n{thought2}")
print(f"\n--- FINAL VERDICT ---\n{verdict2}")

notebook_iframe(viz_page2)

# Example demonstrating flexibility with different target tokens
analyze_and_visualize(
    "Is it True or False that independent pricing is legal?",
    target_tokens=["True", "False"],
    layer_stride=4
)

# Re-running the analysis with the updated function to show top predictions
analyze_and_visualize(
    "Is it True or False that independent pricing is legal?",
    target_tokens=["True", "False"],
    layer_stride=4
)

import pandas as pd
# Re-triggering the consolidated function to show the updated top-token prints and the interactive iframe
analyze_and_visualize(
    "Is it True or False that independent pricing is legal?",
    target_tokens=["True", "False"],
    layer_stride=4
)

# Run Analysis and display Text Results
prompt = "Is it True or False that independent pricing is legal?"
df_conf, thought, verdict, viz_page = analyze_and_visualize(prompt, target_tokens=["True", "False"], layer_stride=4)
print(f"\n--- TARGET TOKEN CONFIDENCE SUMMARY ---")
display(dfconf)
print(f"\n--- MODEL REASONING ---\n{thought}")
print(f"\n--- FINAL VERDICT ---\n{verdict}")



notebook_iframe(viz_page)

# Cell 1: Perform Analysis and Display Text Results
prompt = "Is it True or False that independent pricing is legal?"
df_conf, thought, verdict, viz_page = analyze_and_visualize(
    prompt,
    target_tokens=["True", "False"],
    layer_stride=4
)

print(f"\n--- TARGET TOKEN CONFIDENCE SUMMARY ---")
display(df_conf)
print(f"\n--- MODEL REASONING ---\n{thought}")
print(f"\n--- FINAL VERDICT ---\n{verdict}")

# Example usage:
analyze_prompt_with_lens("Two competitors combine to choose the same price. Illegal? Just answer Yes or no.")

# Example usage:
analyze_prompt_with_lens("Two competitors independently choose the same price. Illegal? Just answer Yes or no.")

# Example usage:
analyze_prompt_with_lens("Two competitors independently choose the same price. Illegal? Just answer Yes or no.")



import gzip
import json
from jlens.vis import build_page, compute_slice, notebook_iframe

# Use the specific prompt we analyzed
prompt_to_viz = "Two competitors independently choose the same price. Illegal? Just answer Yes or no."

# Load the gloss for token translation
gloss = {
    int(k): v for k, v in json.load(gzip.open("/content/jacobian-lens-581d398613e5602a5af361e1c34d3a92ea82ba8e/assets/qwen_gloss.json.gz")).items()
}

# Compute slice for the visualization
slice_data = compute_slice(
    model,
    lens,
    prompt_to_viz,
    layer_stride=2,
    mask_display=True,
)

# Build and display the interactive page
page, _, _ = build_page(
    slice_data,
    prompt_to_viz,
    title="Price-Fixing Legal Analysis",
    description="Visualizing internal transitions for the query: 'Two competitors independently choose the same price.'",
    alt_token=gloss,
)
notebook_iframe(page)